apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "app-ingress"
  namespace: "default"
  annotations:
    networking.gke.io/managed-certificates: "app-certificate"
spec:
  rules:
  - http:
      paths:
      - path: "/*"
        backend:
          serviceName: "app-service"
          servicePort: 80
    host: "realfoodtw.com"